jaegerUrl: "http://my-hunter-jaeger-collector.telemetry.svc.cluster.local:14268/api/traces"
logLevel: "debug"

postgres:
  image: "localhost:5000/scaling-database:latest"

webserver:
  binary: "/ko-app/cmd"
