nameOverride: ""
fullnameOverride: ""


jaegerUrl: ""
logLevel: "info"


loadgen:
  job:
    enabled: true
  deployment:
    enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  binary: ""
  image: "webserver"


webserver:
  host: ""