apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-hunter-hack
spec:
  ingressClassName: nginx
  rules:
  - host: jaeger.local
    http:
      paths:
      - backend:
          service:
            name: my-hunter-jaeger-query
            port:
              number: 16686
        path: /
        pathType: Prefix