controller:

  hostPort:
    enabled: true

  metrics:
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  service:
    type: NodePort
