jaegerUrl: "http://my-hunter-jaeger-collector.telemetry.svc.cluster.local:14268/api/traces"
logLevel: "debug"

loadgen:
  deployment:
    enabled: false
  job:
    enabled: false

postgres:
  psqlHack:
    enabled: true

webserver:
  binary: "/main"
  enabled: true
  image: "localhost:5000/scaling:latest"
