apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadgen.fullname" . }}-loadgen
  labels:
    {{- include "loadgen.deployment.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "loadgen.deployment.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadgen.fullname" . }}-loadgen
  labels:
    {{- include "loadgen.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ if .Values.loadgen.deployment.enabled }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      {{- include "loadgen.deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        {{- include "loadgen.deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "loadgen"
          command: ["{{ .Values.loadgen.binary }}"]
          args: ["loadgen", "/config/config.json"]
          image: "{{ .Values.loadgen.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9876
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /liveness
#              port: http
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            timeoutSeconds: 5
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: http
          resources:
            {{- toYaml .Values.loadgen.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: loadgen-config
