nameOverride: ""
fullnameOverride: ""


jaegerUrl: ""
logLevel: "info"


ingress:
  enabled: true
  className: "nginx"
  host: "scaling-example.local"
  # hosts:
  #   - host: scaling-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - scaling-example.local


loadgen:
  job:
    enabled: true
  deployment:
    enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  mode: "create-users"
  binary: ""
  image: "webserver"
  webserver:
    host: ""


postgres:
  user: "postgres"
  host: "my-pg-postgresql"
  password: "postgres"
  dbname: "scaling"
  image: "docker.io/bitnami/postgresql:14.3.0-debian-10-r20"
  psqlHack:
    enabled: false


webserver:
  binary: ""
  enabled: true
  image: "webserver"

  serviceAccount:
    create: false
    annotations: { }
    name: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
