{{ if .Values.loadgen.deployment.enabled }}
apiVersion: v1
data:
  config.json: |
    {
      "LogLevel": "{{ .Values.logLevel }}",
      "JaegerURL": "{{ .Values.jaegerUrl }}",
      "PrometheusPort": 9090,
      "Webserver": {
        "Host": "{{ include "scaling.fullname" . }}-webserver",
        "ContainerPort": 8765,
        "ServicePort": 80
      },
      "Postgres": {
        "Host": {{ .Values.postgres.host | quote }},
        "User": {{ .Values.postgres.user | quote }},
        "Password": {{ .Values.postgres.password | quote }},
        "Database": {{ .Values.postgres.dbname | quote }}
      },
      "Loadgen": {
        "Mode": "users",
        "Workers": 5,
        "PauseMilliseconds": 500
      }
    }
kind: ConfigMap
metadata:
  name: loadgen-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaling.fullname" . }}-loadgen
  labels:
    {{- include "loadgen.deployment.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "loadgen.deployment.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scaling.fullname" . }}-loadgen
  labels:
    {{- include "loadgen.deployment.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "loadgen.deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        {{- include "loadgen.deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "loadgen"
          command: ["{{ .Values.loadgen.binary }}"]
          args: ["loadgen", "/config/config.json"]
          image: "{{ .Values.loadgen.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9876
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /liveness
#              port: http
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            timeoutSeconds: 5
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: http
          resources:
            {{- toYaml .Values.loadgen.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: loadgen-config
{{- end }}
