apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: loadgen
requires:
  - path: ../server
build:
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: webserver
      context: ../../
      # where does ko put the binary?  see https://github.com/ko-build/ko#build-an-image
      #    look under /ko-app/ for built binary
      ko:
        fromImage: gcr.io/distroless/base:debug-nonroot
        dir: cmd
deploy:
  helm:
    releases:
      - name: my-loadgen
        chartPath: ../../charts/loadgen
        namespace: scaling
        valuesFiles:
          - values.yaml
        artifactOverrides:
          webserver:
            image: webserver
          loadgen:
            image: webserver
