jaegerUrl: "http://my-hunter-jaeger-collector.telemetry.svc.cluster.local:14268/api/traces"
logLevel: "debug"

loadgen:
  binary: "/ko-app/cmd"
  job:
    enabled: true
  deployment:
    enabled: false

webserver:
  host: "my-scaling-server-webserver"
