{{ if .Values.webserver.enabled }}
apiVersion: v1
data:
  config.json: |
    {
      "LogLevel": "{{ .Values.logLevel }}",
      "JaegerURL": "{{ .Values.jaegerUrl }}",
      "PrometheusPort": 9090,
      "Webserver": {
        "Host": "{{ include "scaling.fullname" . }}-webserver",
        "ContainerPort": 8765,
        "ServicePort": 80
      },
      "Postgres": {
        "Host": {{ .Values.postgres.host | quote }},
        "User": {{ .Values.postgres.user | quote }},
        "Password": {{ .Values.postgres.password | quote }},
        "AdminDatabase": "postgres",
        "Database": {{ .Values.postgres.dbname | quote }}
      },
      "Loadgen": {
        "Mode": "canned"
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "scaling.fullname" . }}-scaling-config
{{- end }}