{{ if or .Values.loadgen.deployment.enabled .Values.loadgen.job.enabled }}
apiVersion: v1
data:
  config.json: |
    {
      "LogLevel": "{{ .Values.logLevel }}",
      "JaegerURL": "{{ .Values.jaegerUrl }}",
      "PrometheusPort": 9090,
      "Webserver": {
        "Host": "{{ .Values.loadgen.webserver.host }}",
        "ContainerPort": 8765,
        "ServicePort": 80
      },
      "Loadgen": {
        "Mode": "{{ .Values.loadgen.mode }}",
        "Workers": 5,
        "PauseMilliseconds": 500
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "scaling.fullname" . }}-loadgen-config
{{- end }}
