nameOverride: ""
fullnameOverride: ""


jaegerUrl: ""
logLevel: "info"


ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: scaling-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - scaling-example.local


postgres:
  user: "postgres"
  host: "my-pg-postgresql"
  password: "postgres"
  dbname: "scaling"
  image: "scaling-database"
  initializeJob:
    enabled: true


loadgen:
  job:
    enabled: false
  deployment:
    enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  binary: ""
  image: "webserver"


webserver:
  binary: ""
  enabled: true
  image: "webserver"

  serviceAccount:
    create: false
    annotations: { }
    name: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }
