adminPassword: "grafana-admin"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - scaling.local

sidecar:
  dashboards:
    enabled: true
    provider:
      allowUiUpdates: true
  datasources:
    enabled: true

rbac:
  pspEnabled: false
  pspUseAppArmor: false
